app = "take-home-dawn-star-7575"
primary_region = "gru"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["backend", "frontend"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

# Backend (Python)
[[processes]]
  name = "backend"
  command = "gunicorn -w 4 -b 0.0.0.0:5000 app:app"

[[services]]
  internal_port = 5000
  protocol = "tcp"
  processes = ["backend"]

  [[services.ports]]
    handlers = ["http"]
    port = 5000

[build]
  dockerfile = "backend/Dockerfile"

# Frontend (Next.js)
[[processes]]
  name = "frontend"
  command = "npm run start"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  processes = ["frontend"]

  [[services.ports]]
    handlers = ["http"]
    port = 3000
